name: CI

on:
     push:
          branches: [master, main]
     pull_request:
          branches: [master, main]

jobs:
     test:
          runs-on: ubuntu-latest

          steps:
               - uses: actions/checkout@v4

               - name: Install Rust
                 uses: dtolnay/rust-toolchain@stable

               - name: Cache dependencies
                 uses: Swatinem/rust-cache@v2

               - name: Check formatting
                 run: cargo fmt --check

               - name: Run clippy
                 run: cargo clippy -- -D warnings

               - name: Run tests
                 run: cargo test

               - name: Check build
                 run: cargo build --release
